# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# plugins: rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  DisabledByDefault: false
  NewCops: enable

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - hash

Style/RedundantReturn:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
