plugins:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-performance

AllCops:
  TargetRubyVersion: 4.0
  DisabledByDefault: false
  NewCops: enable

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - hash

Rails/I18nLocaleTexts:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false